# Generated by Django 5.0.1 on 2024-02-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='file_path',
            field=models.FileField(default=0, upload_to='game_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
